name: meditation_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: 0.10.1
  logger: ^1.3.0
  #UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.3
  cached_network_image: ^3.2.3
  #Routing
  auto_route: 5.0.4
  #DI
  kiwi: ^4.1.0
  #Networking
  dio: ^5.0.2
  #State Management
  flutter_bloc: ^8.1.2
  equatable: 2.0.5
  flutter_screenutil: ^5.7.0

  # analyzer: ^5.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #Generator
  kiwi_generator: ^4.1.0
  build_runner: 2.3.3
  auto_route_generator: 5.0.3

# dependency_overrides:
#   analyzer: 5.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
